### ISSUE TITLE
5 minute settlements coming to Amber

### ISSUE THREAD

**Issue by purcell-lab** [melvanderwal/HA-Amber-Electric-Usage-Charts#4]
Great work on an awesome set of charts.

With 5 minute settlements some changes are going to be needed with this automation, I would imagine not dissimilar to what you have created for the LV integration, which is also on 5 minute settlement.

![Screenshot_20241201-113114](https://github.com/user-attachments/assets/2b9be28b-beb0-4508-b851-fad2e7802938)

```
    trigger:
    - platform: time_pattern
      minutes: '4'
      seconds: '58'
    - platform: time_pattern
      minutes: '9'
      seconds: '58'
    - platform: time_pattern
      minutes: '14'
      seconds: '58'
    - platform: time_pattern
      minutes: '19'
      seconds: '58'
    - platform: time_pattern
      minutes: '24'
      seconds: '58'
    - platform: time_pattern
      minutes: '29'
      seconds: '58'
    - platform: time_pattern
      minutes: '34'
      seconds: '58'
    - platform: time_pattern
      minutes: '39'
      seconds: '58'
    - platform: time_pattern
      minutes: '44'
      seconds: '58'
    - platform: time_pattern
      minutes: '49'
      seconds: '58'
    - platform: time_pattern
      minutes: '54'
      seconds: '58'
    - platform: time_pattern
      minutes: '59'
      seconds: '58'
```

and the cron entry:

```
  # Cumulative energy import for each half hour
  inverter_import_energy_30_minutes:  
    unique_id: inverter_import_energy_30_minutes
    name: 'Inverter: Import Energy (30 Minutes)'
    source: sensor.inverter_import_energy_total
    cron: "*/5 * * * *"

  # Cumulative energy export for each half hour
  inverter_export_energy_30_minutes:
    unique_id: inverter_export_energy_30_minutes
    name: 'Inverter: Export Energy (30 Minutes)'
    source: sensor.inverter_export_energy_total
    cron: "*/5 * * * *"
```

I suppose the sensors could also have name changes, but then they will need to be updated elsewhere as well as the charts themselves.
